name: Teros. A way of living.
favicon: null
layout_spectrum: 0.5916127790696919
typography_spectrum: 0.90207
title: Teros. A greener way of living.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c1c0'
    - '#fffffe'
    - '#1786bd'
    - '#b74028'
    - '#ed962e'
  brandStrength: 0.9375
  lightness: 0.5940519417636096
  saturation: 0.5
  rhythmicContrast: 0.3404640720691532
purpose: []
