name: Teros. A way of living.
favicon: null
layout_spectrum: 0.88477
typography_spectrum: 0.63063
title: Teros. A greener way of living.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c1c0'
    - '#fffffe'
    - '#1786bd'
    - '#b74028'
    - '#ed962e'
  brandStrength: 0.7634408
  lightness: 0.5940519417636096
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
